[build]
  # No build command needed - using pre-built static files
  command = ""
  publish = "netlify-app"
  ignore = "false"

# Disable automatic framework detection
[build.environment]
  NETLIFY_SKIP_NEXTJS_PLUGIN = "true"

[[plugins]]
  # Explicitly disable Next.js plugin
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true

[[redirects]]
  from = "/*"
  to = "/course.html"
  status = 200