[build]
  # Move Next.js files temporarily to prevent auto-detection, then deploy static files
  command = "mv package.json package.json.bak 2>/dev/null || true; mv next.config.js next.config.js.bak 2>/dev/null || true"
  publish = "netlify-app"

[[redirects]]
  from = "/*"
  to = "/course.html"
  status = 200