[build]
  command = "npm run build"
  publish = "netlify-app"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/course.html"
  status = 200